name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World !!!"
          echo "My name is Malli"
      - name: Print Goodbye
        run: echo "Done - Bye !!!"
